server {
    listen 80;
    server_name doings.verifytools;
    location /.well-known/acme-challenge/ { root /var/www/html/public; }
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name doings.verifytools;

    ssl_certificate /etc/letsencrypt/live/doings.verifytools/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/doings.verifytools/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    root /var/www/html/public;
    index active.php index.php;

    location / {
        try_files $uri $uri/ /active.php?$query_string;
    }
}
